import com.fasterxml.jackson.module.kotlin.jacksonObjectMapper


/**
 * https://stackoverflow.com/questions/45949584/how-does-the-reified-keyword-in-kotlin-work
 */

// Overloading return type using reified
inline fun <reified T> calculate(value: Float): T {
    return when (T::class) {
        Float::class -> value as T
        Int::class -> value.toInt() as T
        else -> throw IllegalStateException("Only works with Float and Int")
    }
}




// 1. Reified types can be used only with inline functions
// 2. When you call an inline function with reified type,
// the compiler knows the actual type used as a type argument
// and modifies the generated bytecode to use the corresponding class directly
inline fun <reified T : Any> String.toKotlinObject(): T {
    val mapper = jacksonObjectMapper()
    return mapper.readValue(this, T::class.java)
}


fun main() {

    val intCall: Int = calculate<Int>(12.3f)
    val floatCall: Float = calculate<Float>(12.3f)

    println(intCall)
    println(floatCall)

    val string = " {\n" +
            " \t\"color\": \"black\",\n" +
            " \t\"category\": \"hue\",\n" +
            " \t\"type\": \"primary\"\n" +
            " }"
    // Type is Response here
    var response = string.toKotlinObject<Response>()
    println("Color : ${response.color}")
    println("Category : ${response.category}")
    println("Type : ${response.type}")
}

/**
 * In android
 * inline fun <reified T:Any> Context.openActivity(noinline init: Intent.()-> Unit {}) {
 * var intent = newIntent<T>(this)
 * intent.init()
 * startActivity(intent)
 * }
 *
 * inline fun <reified T: Any> newIntent(context: Context): Intent =
 *              Intent(context,T::class.java)
 *
 * Usage : T is resolved to MainActivity
 * openActivity(MyActivity::class.java) {
 * putString("string.key", "string.value")
 * putInt("string.key", 43)
 * }
 */


