import com.fasterxml.jackson.module.kotlin.jacksonObjectMapper


/**
 * https://stackoverflow.com/questions/45949584/how-does-the-reified-keyword-in-kotlin-work
 */


// 1. Reified types can be used only with inline functions
// 2. When you call an inline function with reified type,
// the compiler knows the actual type used as a type argument
// and modifies the generated bytecode to use the corresponding class directly
inline fun <reified T : Any> String.toKotlinObject(): T {
    val mapper = jacksonObjectMapper()
    return mapper.readValue(this, T::class.java)
}


fun main() {


    val string = " {\n" +
            " \t\"color\": \"black\",\n" +
            " \t\"category\": \"hue\",\n" +
            " \t\"type\": \"primary\"\n" +
            " }"
    // Type is Response here
    var response = string.toKotlinObject<Response>()
    println("Color : ${response.color}")
    println("Category : ${response.category}")
    println("Type : ${response.type}")
}

/**
 * In android
 * inline fun <T> Context.openActivity(it: Class<T>, extras: Bundle.() -> Unit = {}) {
 * var intent = Intent(this, it)
 * intent.putExtras(Bundle().apply(extras))
 * startActivity(intent)
 * }
 * Usage : T is resolved to MainActivity
 * openActivity(MyActivity::class.java) {
 * putString("string.key", "string.value")
 * putInt("string.key", 43)
 * }
 */


